### ISSUE TITLE
Separating identity and authentication in the API shape

### ISSUE THREAD

**Issue by hober** [WICG/identity-credential#16] opened 2023-09-06 22:35 UTC
Probably the most straightforward way would be to split something identity-specific off of the existing `navigator.credentials.get()`, which would then be used for non-identity stuff. `navigator.credentials.getIdentity()` maybe?

**Comment by hober** [comment] 2023-09-06 22:36
Maybe this is a dup of #10?

**Comment by RByers** [comment] 2023-09-21 14:12
Thanks Tess. I do think this is a dupe of #10, so I'll follow up there.

**Closed by RByers** 2023-09-21 14:12 UTC
